// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZAn30jpyuq2a6U7XtoqwfXcqdWz5ckc',
    appId: '1:652521202771:web:bcf8e1ebc3d7b981dd12a6',
    messagingSenderId: '652521202771',
    projectId: 'objectdiary-70f1f',
    authDomain: 'objectdiary-70f1f.firebaseapp.com',
    storageBucket: 'objectdiary-70f1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9nCSG4EWocu0TRBi4_Y3Vu3ZzdBUKjY',
    appId: '1:652521202771:android:c7a3799f4411ec64dd12a6',
    messagingSenderId: '652521202771',
    projectId: 'objectdiary-70f1f',
    storageBucket: 'objectdiary-70f1f.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXsFNukOvEeV3MDrFZdvZzvOLEy_s6eU',
    appId: '1:652521202771:ios:823f015f21defe6ddd12a6',
    messagingSenderId: '652521202771',
    projectId: 'objectdiary-70f1f',
    storageBucket: 'objectdiary-70f1f.firebasestorage.app',
    iosClientId: '652521202771-jiq6kogcsik6gk6ch1otfqhtunpddij6.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProj',
  );
}
