name: ObjectDiary CI

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main
      - development

jobs:
  analyze-and-test:
    name: Analyze and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --debug